// Fin 24/7 widget wall — English version of content/pt-BR/fin-wall.ts.
// TODO(content): all values are ILLUSTRATIVE (product mockup), not real
// client or Vispe data.
import type { FinWidget } from "../fin-wall";

export const finWall: readonly FinWidget[] = [
  // — linha 1
  {
    id: "cash-flow-30d",
    kind: "sparkline",
    size: "l",
    label: "Cash flow · 30 days",
    value: "+R$ 48,320",
    points: [12, 18, 15, 22, 20, 28, 25, 31, 29, 36, 34, 41],
    compare: [10, 12, 14, 13, 17, 16, 19, 21, 20, 23, 22, 25],
    axis: ["Sep 01", "Sep 30"],
  },
  { id: "in-today", kind: "stat", size: "s", label: "Inflows", value: "18k", icon: "in" },
  { id: "out-today", kind: "stat", size: "s", label: "Outflows", value: "9.4k", icon: "out" },
  {
    id: "balance",
    kind: "stat",
    size: "m",
    label: "Consolidated balance",
    value: "R$ 312,480",
    icon: "wallet",
    delta: { text: "+2.4% today", trend: "up" },
  },
  { id: "net-margin", kind: "gauge", size: "s", label: "Net margin", value: 18, display: "18%", tone: "brand" },
  {
    id: "calendar",
    kind: "calendar",
    size: "m",
    month: "October",
    days: [
      { weekday: "Mon", day: "06" },
      { weekday: "Tue", day: "07" },
      { weekday: "Wed", day: "08" },
      { weekday: "Thu", day: "09" },
      { weekday: "Fri", day: "10" },
    ],
    active: 2,
  },

  // — linha 2
  {
    id: "payables",
    kind: "list",
    size: "m",
    rows: [
      { label: "Supplier A", value: "Today", marker: "open", tone: "default" },
      { label: "Rent", value: "Tomorrow", marker: "open", tone: "muted" },
      { label: "Utilities", value: "Overdue", marker: "open", tone: "accent" },
    ],
  },
  {
    id: "cash-runway",
    kind: "progress",
    size: "m",
    label: "Cash runway",
    display: "4.2 months",
    value: 70,
    caption: "Fixed costs covered",
  },
  { id: "clock", kind: "clock", size: "s" },
  {
    id: "income-statement",
    kind: "list",
    size: "m",
    title: "P&L · September",
    rows: [
      { label: "Revenue", value: "R$ 186k" },
      { label: "Costs", value: "−R$ 121k", tone: "muted" },
      { label: "Profit", value: "R$ 65k", tone: "brand" },
    ],
  },
  { id: "default-rate", kind: "gauge", size: "s", label: "Default rate", value: 3, display: "3%", tone: "accent" },
  {
    id: "cash-alert",
    kind: "notification",
    size: "m",
    icon: "alert",
    eyebrow: "Cash alert",
    title: "Balance below minimum",
    body: "Projected in 12 days",
  },

  // — linha 3
  {
    id: "revenue",
    kind: "stat",
    size: "m",
    label: "Monthly revenue",
    value: "R$ 186,200",
    icon: "trend",
    delta: { text: "+12% vs August", trend: "up" },
  },
  { id: "gross-margin", kind: "gauge", size: "s", label: "Gross margin", value: 42, display: "42%", tone: "default" },
  {
    id: "ytd-profit",
    kind: "sparkline",
    size: "l",
    label: "Profit YTD · 2026",
    value: "R$ 512,900",
    points: [8, 14, 19, 27, 33, 38, 46, 52, 61],
    delta: "+21% this year",
    axis: ["Jan", "Sep"],
  },
  { id: "revenue-goal", kind: "gauge", size: "s", label: "Goal", value: 82, display: "82%", tone: "brand" },
  {
    id: "bank-balances",
    kind: "list",
    size: "m",
    title: "Balance by bank",
    rows: [
      { label: "Bank 1", value: "R$ 184k", marker: "dot" },
      { label: "Bank 2", value: "R$ 96k", marker: "dot" },
      { label: "Bank 3", value: "R$ 32k", marker: "dot" },
    ],
    hideOnMobile: true,
  },

  // — linha 4
  {
    id: "next-due",
    kind: "event",
    size: "m",
    day: "15",
    month: "Oct",
    title: "Payroll",
    detail: "Next due date",
    value: "R$ 42k",
    hideOnMobile: true,
  },
  {
    id: "expenses-by-category",
    kind: "bars",
    size: "m",
    title: "Expenses by category",
    bars: [
      { label: "Payroll", value: 82 },
      { label: "Taxes", value: 54 },
      { label: "Operations", value: 37 },
    ],
  },
  { id: "tax-regime", kind: "badge", size: "s", icon: "shield", label: "Presumed", hideOnMobile: true },
  {
    id: "ebitda",
    kind: "sparkline",
    size: "m",
    label: "EBITDA",
    value: "R$ 71k",
    points: [20, 24, 22, 27, 30, 29, 34],
    hideOnMobile: true,
  },
  { id: "reconciliation", kind: "badge", size: "s", icon: "check", label: "98%" },
  {
    id: "payment-confirmed",
    kind: "notification",
    size: "m",
    icon: "receipt",
    eyebrow: "Just now",
    title: "Payment confirmed",
    body: "Client invoice paid",
  },

  // — linha 5
  {
    id: "receivables",
    kind: "list",
    size: "m",
    title: "Receivables",
    rows: [
      { label: "Client A", value: "R$ 12.4k" },
      { label: "Client B", value: "R$ 8.9k" },
      { label: "Client C", value: "R$ 5.1k" },
    ],
    hideOnMobile: true,
  },
  { id: "avg-ticket", kind: "stat", size: "s", label: "Avg. ticket", value: "2.8k", icon: "receipt", hideOnMobile: true },
  {
    id: "break-even",
    kind: "progress",
    size: "m",
    label: "Break-even point",
    display: "78%",
    value: 78,
    caption: "Reached this month",
    hideOnMobile: true,
  },
  {
    id: "taxes",
    kind: "list",
    size: "m",
    title: "Taxes this month",
    rows: [
      { label: "PIS/COFINS", value: "R$ 6.8k" },
      { label: "ISS", value: "R$ 3.7k" },
      { label: "Total", value: "R$ 14.2k", tone: "brand" },
    ],
    hideOnMobile: true,
  },
  { id: "fixed-cost", kind: "stat", size: "s", label: "Fixed cost", value: "58k", icon: "bank", hideOnMobile: true },
  {
    id: "tax-savings",
    kind: "stat",
    size: "m",
    label: "Tax savings this year",
    value: "R$ 38,600",
    icon: "piggy",
    hideOnMobile: true,
  },

  // — linha 6
  { id: "search", kind: "search", size: "m", placeholder: "Search transactions…", hideOnMobile: true },
  {
    id: "monthly-report",
    kind: "notification",
    size: "m",
    icon: "file",
    eyebrow: "Report ready",
    title: "September closing",
    body: "PDF · 12 pages",
    hideOnMobile: true,
  },
  {
    id: "cfo-meeting",
    kind: "event",
    size: "m",
    day: "09",
    month: "Oct",
    title: "Monthly review with the CFO",
    detail: "10:00 – 11:00",
    hideOnMobile: true,
  },
  {
    id: "tasks",
    kind: "list",
    size: "m",
    rows: [
      { label: "Reconcile statements", marker: "done", tone: "muted" },
      { label: "Approve payments", marker: "open" },
      { label: "Issue invoices", marker: "open" },
    ],
    hideOnMobile: true,
  },
  {
    id: "market",
    kind: "list",
    size: "m",
    title: "Indicators",
    rows: [
      { label: "Selic", value: "—" },
      { label: "IPCA 12m", value: "—" },
      { label: "CDI", value: "—" },
    ],
    hideOnMobile: true,
  },
];
